import type { Category, Occasion, Product, ProductColor } from "../features/catalog/types";

const C = {
  blanco: { name: "Blanco", hex: "#FFFFFF" },
  negro: { name: "Negro", hex: "#1F2125" },
  gris: { name: "Gris jaspeado", hex: "#B8BCC4" },
  rojo: { name: "Rojo", hex: "#E5383B" },
  verde: { name: "Verde", hex: "#3FA36B" },
  rosa: { name: "Rosa", hex: "#F7A8C8" },
  fucsia: { name: "Fucsia", hex: "#EC1E79" },
  azul: { name: "Azul", hex: "#2F7BEA" },
  marino: { name: "Azul marino", hex: "#1E2A4A" },
  natural: { name: "Natural", hex: "#EFE4CF" },
  beige: { name: "Beige", hex: "#D8C3A0" },
  salvia: { name: "Salvia", hex: "#A9C4B1" },
  lila: { name: "Lila", hex: "#C9B6F2" },
  amarillo: { name: "Amarillo", hex: "#FFD45C" },
} satisfies Record<string, ProductColor>;

const ADULT = ["S", "M", "L", "XL", "XXL"];
const KIDS = ["2-4 años", "4-6 años", "6-8 años", "8-10 años"];
const BABY = ["0-3 m", "3-6 m", "6-12 m", "12-18 m"];

export const seedCategories: Category[] = (
  [
  { slug: "camisetas", name: "Camisetas", kind: "tshirt", tint: "#CFF3F4", description: "Camisetas de algodón con tu diseño, para todas las edades." },
  { slug: "sudaderas", name: "Sudaderas", kind: "hoodie", tint: "#EBDDD7", description: "Sudaderas con y sin capucha, calentitas y 100% tuyas." },
  { slug: "tazas", name: "Tazas", kind: "mug", tint: "#DCDDFB", description: "Tazas de cerámica para el desayuno más especial." },
  { slug: "gorras", name: "Gorras", kind: "cap", tint: "#FFD9A8", description: "Gorras con frase, logo o el diseño que imagines." },
  { slug: "bolsas", name: "Bolsas y tote bags", kind: "tote", tint: "#FFF0B3", description: "Tote bags resistentes para llevar tu estilo a todas partes." },
  { slug: "botellas", name: "Botellas y termos", kind: "bottle", tint: "#D3F2E1", description: "Botellas y termos reutilizables con tu nombre o diseño." },
  { slug: "regalos", name: "Regalos personalizados", kind: "gift", tint: "#FFD3DE", description: "Packs y detalles únicos para cada ocasión especial." },
  { slug: "bebes-ninos", name: "Bebés y niños", kind: "bodysuit", tint: "#D3ECFA", description: "Bodies y camisetas infantiles con nombres y dibujos." },
  { slug: "empresas", name: "Empresas y eventos", kind: "polo", tint: "#CBE6F5", description: "Ropa laboral, merchandising y regalos corporativos." },
  { slug: "otros", name: "Otros productos", kind: "cushion", tint: "#EADFFB", description: "Cojines, delantales y mucho más por descubrir." },
  ] satisfies Omit<Category, "imageUrl">[]
).map((category) => ({ ...category, imageUrl: null }));

export const seedOccasions: Occasion[] = [
  { slug: "mama", name: "Para mamá", emoji: "❤️", tint: "#FFD3DE", blurb: "Porque ella se merece un regalo tan único como su amor." },
  { slug: "papa", name: "Para papá", emoji: "👔", tint: "#CBE6F5", blurb: "Detalles con su foto, su frase o su equipo favorito." },
  { slug: "parejas", name: "Para parejas", emoji: "💑", tint: "#FFE0EC", blurb: "Diseños a juego para los que lo comparten todo." },
  { slug: "cumpleanos", name: "Cumpleaños", emoji: "🎂", tint: "#FFF0B3", blurb: "Sorprende con un regalo que nadie más tendrá." },
  { slug: "bodas", name: "Bodas", emoji: "💍", tint: "#F4ECE1", blurb: "Detalles para invitados, despedidas y recién casados." },
  { slug: "comuniones", name: "Comuniones", emoji: "🕊️", tint: "#E3F1FB", blurb: "Recuerdos personalizados para un día inolvidable." },
  { slug: "bautizos", name: "Bautizos", emoji: "👶", tint: "#D3ECFA", blurb: "Bodies, bolsas y detalles para dar la bienvenida." },
  { slug: "navidad", name: "Navidad", emoji: "🎄", tint: "#D3F2E1", blurb: "Tazas, sudaderas y regalos con espíritu navideño." },
  { slug: "profesores", name: "Profesores", emoji: "🍎", tint: "#FFE7CC", blurb: "El gracias perfecto para fin de curso." },
  { slug: "despedidas", name: "Despedidas", emoji: "🎉", tint: "#EADFFB", blurb: "Camisetas de grupo para una despedida épica." },
  { slug: "aniversarios", name: "Aniversarios", emoji: "🥂", tint: "#FFD9E6", blurb: "Celebra vuestra historia con vuestras fotos." },
  { slug: "mascotas", name: "Mascotas", emoji: "🐾", tint: "#EBDDD7", blurb: "Tu peludo estampado en tazas, cojines y más." },
  { slug: "empresas", name: "Regalos para empresas", emoji: "🏢", tint: "#DCDDFB", blurb: "Detalles corporativos para clientes y equipos." },
];

type SeedProduct = Omit<Product, "badge" | "featured" | "images"> & Partial<Pick<Product, "badge" | "featured">>;

const products: SeedProduct[] = [
  {
    slug: "camiseta-personalizada",
    name: "Camiseta personalizada",
    summary: "Camiseta 100% algodón con tu foto, frase o diseño.",
    description: "Camiseta unisex de algodón peinado de 180 g, suave y resistente al lavado. Estampamos tu diseño en DTF a todo color, con acabado flexible que no se agrieta.",
    categorySlug: "camisetas",
    kind: "tshirt",
    priceCents: 1990,
    colors: [C.blanco, C.negro, C.fucsia, C.rosa, C.gris, C.azul],
    sizes: ADULT,
    occasions: ["mama", "papa", "parejas", "cumpleanos", "despedidas"],
    art: "heart",
    badge: "Más vendido",
    featured: true,
  },
  {
    slug: "taza-personalizada",
    name: "Taza personalizada",
    summary: "Taza de cerámica de 330 ml con tu foto o mensaje.",
    description: "Taza de cerámica blanca de 330 ml apta para lavavajillas y microondas. Sublimación de alta definición: los colores no se van con el uso.",
    categorySlug: "tazas",
    kind: "mug",
    priceCents: 1290,
    colors: [C.blanco, C.negro, C.rosa, C.azul],
    sizes: [],
    occasions: ["mama", "papa", "profesores", "navidad", "mascotas", "cumpleanos"],
    art: "familia",
    featured: true,
  },
  {
    slug: "sudadera-personalizada",
    name: "Sudadera personalizada",
    summary: "Sudadera con capucha y bolsillo canguro, con tu diseño.",
    description: "Sudadera con capucha de 280 g, interior perchado y bolsillo canguro. Perfecta para grupos, regalos o para darte un capricho.",
    categorySlug: "sudaderas",
    kind: "hoodie",
    priceCents: 2990,
    colors: [C.negro, C.blanco, C.gris, C.rosa, C.marino],
    sizes: ADULT,
    occasions: ["parejas", "navidad", "cumpleanos", "despedidas"],
    art: "goodvibes",
    featured: true,
  },
  {
    slug: "bolsa-personalizada",
    name: "Bolsa personalizada",
    summary: "Tote bag de algodón natural, resistente y reutilizable.",
    description: "Tote bag de algodón de 140 g con asas largas. Ideal para el día a día, la playa o como detalle para invitados.",
    categorySlug: "bolsas",
    kind: "tote",
    priceCents: 1490,
    colors: [C.natural, C.blanco, C.negro, C.marino],
    sizes: [],
    occasions: ["mama", "profesores", "bodas", "comuniones"],
    art: "sonrie",
    featured: true,
  },
  {
    slug: "botella-personalizada",
    name: "Botella personalizada",
    summary: "Botella de aluminio de 500 ml con tu nombre o frase.",
    description: "Botella reutilizable de aluminio de 500 ml con tapón de rosca. Ligera, sin BPA y personalizada con grabado a color.",
    categorySlug: "botellas",
    kind: "bottle",
    priceCents: 1690,
    colors: [C.rosa, C.marino, C.fucsia, C.blanco, C.salvia],
    sizes: [],
    occasions: ["profesores", "cumpleanos", "empresas"],
    art: "disfruta",
    featured: true,
  },
  {
    slug: "gorra-personalizada",
    name: "Gorra personalizada",
    summary: "Gorra ajustable de algodón con tu logo o frase.",
    description: "Gorra de 6 paneles con cierre ajustable. Estampado o bordado frontal para equipos, eventos o tu estilo propio.",
    categorySlug: "gorras",
    kind: "cap",
    priceCents: 1590,
    colors: [C.negro, C.beige, C.blanco, C.marino],
    sizes: [],
    occasions: ["papa", "despedidas", "empresas"],
    art: "aventura",
    featured: true,
  },
  {
    slug: "termo-acero",
    name: "Termo de acero",
    summary: "Termo de doble pared: frío 24 h, caliente 12 h.",
    description: "Termo de acero inoxidable de 500 ml con doble pared al vacío. Personalizado con tu nombre, logo o diseño.",
    categorySlug: "botellas",
    kind: "bottle",
    priceCents: 2290,
    colors: [C.blanco, C.negro, C.salvia, C.lila],
    sizes: [],
    occasions: ["papa", "profesores", "empresas", "navidad"],
    art: "sun",
  },
  {
    slug: "taza-magica",
    name: "Taza mágica",
    summary: "Negra en frío, revela tu foto al echar algo caliente.",
    description: "Taza termosensible de 330 ml: es negra hasta que le echas una bebida caliente y aparece tu diseño. Sorpresa garantizada.",
    categorySlug: "tazas",
    kind: "mug",
    priceCents: 1590,
    colors: [C.negro],
    sizes: [],
    occasions: ["parejas", "aniversarios", "cumpleanos"],
    art: "heart",
    badge: "Nuevo",
  },
  {
    slug: "camiseta-infantil",
    name: "Camiseta infantil",
    summary: "Camiseta suave para peques, con su nombre o dibujo.",
    description: "Camiseta infantil de algodón 100% con tintas certificadas Oeko-Tex. Sus dibujos convertidos en camiseta.",
    categorySlug: "bebes-ninos",
    kind: "tshirt",
    priceCents: 1590,
    colors: [C.blanco, C.amarillo, C.azul, C.rosa],
    sizes: KIDS,
    occasions: ["cumpleanos", "comuniones"],
    art: "sun",
  },
  {
    slug: "body-bebe",
    name: "Body de bebé",
    summary: "Body de algodón orgánico con mensaje personalizado.",
    description: "Body de manga corta en algodón orgánico, con corchetes en la entrepierna. El regalo estrella para nacimientos y bautizos.",
    categorySlug: "bebes-ninos",
    kind: "bodysuit",
    priceCents: 1490,
    colors: [C.blanco, C.rosa, C.azul, C.salvia],
    sizes: BABY,
    occasions: ["bautizos", "mama", "papa"],
    art: "heart",
  },
  {
    slug: "pack-regalo",
    name: "Pack regalo sorpresa",
    summary: "Caja regalo con taza + bolsa personalizadas y tarjeta.",
    description: "Caja regalo con lazo que incluye una taza y una tote bag personalizadas, más una tarjeta con tu dedicatoria. Lista para regalar.",
    categorySlug: "regalos",
    kind: "gift",
    priceCents: 2490,
    colors: [C.rosa, C.blanco, C.rojo],
    sizes: [],
    occasions: ["mama", "aniversarios", "cumpleanos", "navidad", "parejas"],
    art: "heart",
    badge: "Regalo top",
  },
  {
    slug: "cojin-personalizado",
    name: "Cojín personalizado",
    summary: "Cojín 40×40 cm con tu foto favorita. Relleno incluido.",
    description: "Funda de tacto melocotón de 40×40 cm con relleno incluido. Tus recuerdos, tu mascota o tu frase favorita en el sofá.",
    categorySlug: "otros",
    kind: "cushion",
    priceCents: 1790,
    colors: [C.blanco, C.beige, C.lila],
    sizes: [],
    occasions: ["mascotas", "aniversarios", "parejas", "mama"],
    art: "paw",
  },
  {
    slug: "polo-empresa",
    name: "Polo para empresa",
    summary: "Polo piqué con el logo de tu marca. Ropa laboral.",
    description: "Polo de piqué de 210 g con cuello y puños de canalé. Estampado o bordado del logo en pecho y espalda. Descuentos por volumen.",
    categorySlug: "empresas",
    kind: "polo",
    priceCents: 2190,
    colors: [C.blanco, C.negro, C.marino, C.rojo, C.verde],
    sizes: ADULT,
    occasions: ["empresas"],
    art: "logo",
  },
  {
    slug: "camiseta-merchandising",
    name: "Camiseta merchandising",
    summary: "Camiseta básica para eventos, equipos y promociones.",
    description: "Camiseta de 150 g pensada para pedidos grandes: eventos, carreras, ferias y equipos. Precio por unidad desde 25 uds.",
    categorySlug: "empresas",
    kind: "tshirt",
    priceCents: 990,
    colors: [C.blanco, C.negro, C.rojo, C.azul, C.verde, C.amarillo],
    sizes: ADULT,
    occasions: ["empresas", "despedidas"],
    art: "logo",
  },
];

export const seedProducts: Product[] = products.map((product) => ({
  badge: null,
  featured: false,
  images: [],
  ...product,
}));
